//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class AgoraContext : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AgoraContext(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AgoraContext obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~AgoraContext() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_AgoraContext(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int bSFEncoder {
    set {
      AoceWrapperPINVOKE.AgoraContext_bSFEncoder_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.AgoraContext_bSFEncoder_get(swigCPtr);
      return ret;
    } 
  }

  public int bLoopback {
    set {
      AoceWrapperPINVOKE.AgoraContext_bLoopback_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.AgoraContext_bLoopback_get(swigCPtr);
      return ret;
    } 
  }

  public AgoraContext() : this(AoceWrapperPINVOKE.new_AgoraContext(), true) {
  }

}
