/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_AoceWrapper_WRAP_H_
#define SWIG_AoceWrapper_WRAP_H_

class SwigDirector_ILiveObserver : public aoce::ILiveObserver, public Swig::Director {

public:
    SwigDirector_ILiveObserver();
    virtual ~SwigDirector_ILiveObserver();
    virtual void onEvent(int32_t operater, int32_t code, aoce::LogLevel level, char const *msg);
    virtual void onInitRoom();
    virtual void onLoginRoom(bool bReConnect = false);
    virtual void onUserChange(int32_t userId, bool bAdd);
    virtual void onStreamUpdate(int32_t index, bool bAdd, int32_t code);
    virtual void onStreamUpdate(int32_t userId, int32_t index, bool bAdd, int32_t code);
    virtual void onVideoFrame(int32_t userId, int32_t index, aoce::VideoFrame const &videoFrame);
    virtual void onAudioFrame(int32_t userId, int32_t index, aoce::AudioFrame const &audioFrame);
    virtual void onPlayVolume(int32_t userId, int32_t index, float volume);
    virtual void onPushQuality(int32_t index, int32_t quality, float fps, float kbs);
    virtual void onPullQuality(int32_t userId, int32_t index, int32_t quality, float fps, float kbs);
    virtual void onLogoutRoom();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int, int, int, char *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(int, unsigned int, int);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(int, int, unsigned int, int);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(int, int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(int, int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)(int, int, float);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(int, int, float, float);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(int, int, int, float, float);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)();
    void swig_connect_director(SWIG_Callback0_t callbackonEvent, SWIG_Callback1_t callbackonInitRoom, SWIG_Callback2_t callbackonLoginRoom__SWIG_0, SWIG_Callback3_t callbackonLoginRoom__SWIG_1, SWIG_Callback4_t callbackonUserChange, SWIG_Callback5_t callbackonStreamUpdate__SWIG_0, SWIG_Callback6_t callbackonStreamUpdate__SWIG_1, SWIG_Callback7_t callbackonVideoFrame, SWIG_Callback8_t callbackonAudioFrame, SWIG_Callback9_t callbackonPlayVolume, SWIG_Callback10_t callbackonPushQuality, SWIG_Callback11_t callbackonPullQuality, SWIG_Callback12_t callbackonLogoutRoom);

private:
    SWIG_Callback0_t swig_callbackonEvent;
    SWIG_Callback1_t swig_callbackonInitRoom;
    SWIG_Callback2_t swig_callbackonLoginRoom__SWIG_0;
    SWIG_Callback3_t swig_callbackonLoginRoom__SWIG_1;
    SWIG_Callback4_t swig_callbackonUserChange;
    SWIG_Callback5_t swig_callbackonStreamUpdate__SWIG_0;
    SWIG_Callback6_t swig_callbackonStreamUpdate__SWIG_1;
    SWIG_Callback7_t swig_callbackonVideoFrame;
    SWIG_Callback8_t swig_callbackonAudioFrame;
    SWIG_Callback9_t swig_callbackonPlayVolume;
    SWIG_Callback10_t swig_callbackonPushQuality;
    SWIG_Callback11_t swig_callbackonPullQuality;
    SWIG_Callback12_t swig_callbackonLogoutRoom;
    void swig_init_callbacks();
};

class SwigDirector_IMediaPlayerObserver : public aoce::IMediaPlayerObserver, public Swig::Director {

public:
    SwigDirector_IMediaPlayerObserver();
    virtual ~SwigDirector_IMediaPlayerObserver();
    virtual void onPrepared();
    virtual void onError(aoce::PlayStatus staus, int32_t code, char const *msg);
    virtual void onVideoFrame(aoce::VideoFrame const &frame);
    virtual void onAudioFrame(aoce::AudioFrame const &frame);
    virtual void onStop();
    virtual void onComplate();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(int, int, char *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)();
    void swig_connect_director(SWIG_Callback0_t callbackonPrepared, SWIG_Callback1_t callbackonError, SWIG_Callback2_t callbackonVideoFrame, SWIG_Callback3_t callbackonAudioFrame, SWIG_Callback4_t callbackonStop, SWIG_Callback5_t callbackonComplate);

private:
    SWIG_Callback0_t swig_callbackonPrepared;
    SWIG_Callback1_t swig_callbackonError;
    SWIG_Callback2_t swig_callbackonVideoFrame;
    SWIG_Callback3_t swig_callbackonAudioFrame;
    SWIG_Callback4_t swig_callbackonStop;
    SWIG_Callback5_t swig_callbackonComplate;
    void swig_init_callbacks();
};

class SwigDirector_IVideoDeviceObserver : public aoce::IVideoDeviceObserver, public Swig::Director {

public:
    SwigDirector_IVideoDeviceObserver();
    virtual ~SwigDirector_IVideoDeviceObserver();
    virtual void onDeviceHandle(aoce::VideoHandleId id, int32_t codeId);
    virtual void onVideoFrame(aoce::VideoFrame frame);
    virtual void onDepthVideoFrame(aoce::VideoFrame colorFrame, aoce::VideoFrame depthFrame, void *alignParamt);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int, int);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackonDeviceHandle, SWIG_Callback1_t callbackonVideoFrame, SWIG_Callback2_t callbackonDepthVideoFrame);

private:
    SWIG_Callback0_t swig_callbackonDeviceHandle;
    SWIG_Callback1_t swig_callbackonVideoFrame;
    SWIG_Callback2_t swig_callbackonDepthVideoFrame;
    void swig_init_callbacks();
};

class SwigDirector_IOutputLayerObserver : public aoce::IOutputLayerObserver, public Swig::Director {

public:
    SwigDirector_IOutputLayerObserver();
    virtual ~SwigDirector_IOutputLayerObserver();
    virtual void onImageProcess(uint8_t *data, aoce::ImageFormat const &imageFormat, int32_t outIndex);
    virtual void onFormatChanged(aoce::ImageFormat const &imageFormat, int32_t outIndex);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, int);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *, int);
    void swig_connect_director(SWIG_Callback0_t callbackonImageProcess, SWIG_Callback1_t callbackonFormatChanged);

private:
    SWIG_Callback0_t swig_callbackonImageProcess;
    SWIG_Callback1_t swig_callbackonFormatChanged;
    void swig_init_callbacks();
};

class SwigDirector_ICaptureObserver : public aoce::ICaptureObserver, public Swig::Director {

public:
    SwigDirector_ICaptureObserver();
    virtual ~SwigDirector_ICaptureObserver();
    virtual void onEvent(aoce::CaptureEventId eventId, aoce::LogLevel level, char const *msg);
    virtual void onResize(int32_t width, int32_t height);
    virtual void onCapture(aoce::VideoFormat const &videoFormat, void *device, void *texture);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int, int, char *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(int, int);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackonEvent, SWIG_Callback1_t callbackonResize, SWIG_Callback2_t callbackonCapture);

private:
    SWIG_Callback0_t swig_callbackonEvent;
    SWIG_Callback1_t swig_callbackonResize;
    SWIG_Callback2_t swig_callbackonCapture;
    void swig_init_callbacks();
};

class SwigDirector_IAudioDeviceObserver : public aoce::IAudioDeviceObserver, public Swig::Director {

public:
    SwigDirector_IAudioDeviceObserver();
    virtual ~SwigDirector_IAudioDeviceObserver();
    virtual void onDeviceHandle(aoce::VideoHandleId id, int32_t codeId);
    virtual void onAudioFrame(aoce::AudioFrame const &audioFrame);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int, int);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackonDeviceHandle, SWIG_Callback1_t callbackonAudioFrame);

private:
    SWIG_Callback0_t swig_callbackonDeviceHandle;
    SWIG_Callback1_t swig_callbackonAudioFrame;
    void swig_init_callbacks();
};

class SwigDirector_ILogObserver : public aoce::ILogObserver, public Swig::Director {

public:
    SwigDirector_ILogObserver();
    virtual ~SwigDirector_ILogObserver();
    virtual void onLogEvent(int level, char const *message);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int, char *);
    void swig_connect_director(SWIG_Callback0_t callbackonLogEvent);

private:
    SWIG_Callback0_t swig_callbackonLogEvent;
    void swig_init_callbacks();
};

class SwigDirector_IMotionDetectorObserver : public aoce::IMotionDetectorObserver, public Swig::Director {

public:
    SwigDirector_IMotionDetectorObserver();
    virtual ~SwigDirector_IMotionDetectorObserver();
    virtual void onMotion(aoce::vec4 const &vec);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackonMotion);

private:
    SWIG_Callback0_t swig_callbackonMotion;
    void swig_init_callbacks();
};


#endif
