//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class AudioStream : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AudioStream(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AudioStream obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~AudioStream() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_AudioStream(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public AudioCodec codec {
    set {
      AoceWrapperPINVOKE.AudioStream_codec_set(swigCPtr, (int)value);
    } 
    get {
      AudioCodec ret = (AudioCodec)AoceWrapperPINVOKE.AudioStream_codec_get(swigCPtr);
      return ret;
    } 
  }

  public int channel {
    set {
      AoceWrapperPINVOKE.AudioStream_channel_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.AudioStream_channel_get(swigCPtr);
      return ret;
    } 
  }

  public int sampleRate {
    set {
      AoceWrapperPINVOKE.AudioStream_sampleRate_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.AudioStream_sampleRate_get(swigCPtr);
      return ret;
    } 
  }

  public int depth {
    set {
      AoceWrapperPINVOKE.AudioStream_depth_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.AudioStream_depth_get(swigCPtr);
      return ret;
    } 
  }

  public int bitrate {
    set {
      AoceWrapperPINVOKE.AudioStream_bitrate_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.AudioStream_bitrate_get(swigCPtr);
      return ret;
    } 
  }

  public AudioStream() : this(AoceWrapperPINVOKE.new_AudioStream(), true) {
  }

}
