//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class AudioFormat : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AudioFormat(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AudioFormat obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~AudioFormat() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_AudioFormat(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int channel {
    set {
      AoceWrapperPINVOKE.AudioFormat_channel_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.AudioFormat_channel_get(swigCPtr);
      return ret;
    } 
  }

  public int sampleRate {
    set {
      AoceWrapperPINVOKE.AudioFormat_sampleRate_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.AudioFormat_sampleRate_get(swigCPtr);
      return ret;
    } 
  }

  public int depth {
    set {
      AoceWrapperPINVOKE.AudioFormat_depth_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.AudioFormat_depth_get(swigCPtr);
      return ret;
    } 
  }

  public AudioFormat() : this(AoceWrapperPINVOKE.new_AudioFormat(), true) {
  }

}
