//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class BilateralParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BilateralParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BilateralParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BilateralParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_BilateralParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int kernelSize {
    set {
      AoceWrapperPINVOKE.BilateralParamet_kernelSize_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.BilateralParamet_kernelSize_get(swigCPtr);
      return ret;
    } 
  }

  public float sigma_spatial {
    set {
      AoceWrapperPINVOKE.BilateralParamet_sigma_spatial_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.BilateralParamet_sigma_spatial_get(swigCPtr);
      return ret;
    } 
  }

  public float sigma_color {
    set {
      AoceWrapperPINVOKE.BilateralParamet_sigma_color_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.BilateralParamet_sigma_color_get(swigCPtr);
      return ret;
    } 
  }

  public BilateralParamet() : this(AoceWrapperPINVOKE.new_BilateralParamet(), true) {
  }

}
