//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class BlurSelectiveParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BlurSelectiveParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BlurSelectiveParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BlurSelectiveParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_BlurSelectiveParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public GaussianBlurParamet gaussian {
    set {
      AoceWrapperPINVOKE.BlurSelectiveParamet_gaussian_set(swigCPtr, GaussianBlurParamet.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.BlurSelectiveParamet_gaussian_get(swigCPtr);
      GaussianBlurParamet ret = (cPtr == global::System.IntPtr.Zero) ? null : new GaussianBlurParamet(cPtr, false);
      return ret;
    } 
  }

  public SelectiveParamet blurPosition {
    set {
      AoceWrapperPINVOKE.BlurSelectiveParamet_blurPosition_set(swigCPtr, SelectiveParamet.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.BlurSelectiveParamet_blurPosition_get(swigCPtr);
      SelectiveParamet ret = (cPtr == global::System.IntPtr.Zero) ? null : new SelectiveParamet(cPtr, false);
      return ret;
    } 
  }

  public BlurSelectiveParamet() : this(AoceWrapperPINVOKE.new_BlurSelectiveParamet(), true) {
  }

}
