//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CannyEdgeDetectionParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CannyEdgeDetectionParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CannyEdgeDetectionParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CannyEdgeDetectionParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_CannyEdgeDetectionParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public GaussianBlurParamet blueParamet {
    set {
      AoceWrapperPINVOKE.CannyEdgeDetectionParamet_blueParamet_set(swigCPtr, GaussianBlurParamet.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.CannyEdgeDetectionParamet_blueParamet_get(swigCPtr);
      GaussianBlurParamet ret = (cPtr == global::System.IntPtr.Zero) ? null : new GaussianBlurParamet(cPtr, false);
      return ret;
    } 
  }

  public float minThreshold {
    set {
      AoceWrapperPINVOKE.CannyEdgeDetectionParamet_minThreshold_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.CannyEdgeDetectionParamet_minThreshold_get(swigCPtr);
      return ret;
    } 
  }

  public float maxThreshold {
    set {
      AoceWrapperPINVOKE.CannyEdgeDetectionParamet_maxThreshold_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.CannyEdgeDetectionParamet_maxThreshold_get(swigCPtr);
      return ret;
    } 
  }

  public CannyEdgeDetectionParamet() : this(AoceWrapperPINVOKE.new_CannyEdgeDetectionParamet(), true) {
  }

}
