//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ChromaKeyParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ChromaKeyParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChromaKeyParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ChromaKeyParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_ChromaKeyParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float lumaMask {
    set {
      AoceWrapperPINVOKE.ChromaKeyParamet_lumaMask_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.ChromaKeyParamet_lumaMask_get(swigCPtr);
      return ret;
    } 
  }

  public vec3 chromaColor {
    set {
      AoceWrapperPINVOKE.ChromaKeyParamet_chromaColor_set(swigCPtr, vec3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.ChromaKeyParamet_chromaColor_get(swigCPtr);
      vec3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new vec3(cPtr, false);
      return ret;
    } 
  }

  public float ambientScale {
    set {
      AoceWrapperPINVOKE.ChromaKeyParamet_ambientScale_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.ChromaKeyParamet_ambientScale_get(swigCPtr);
      return ret;
    } 
  }

  public vec3 ambientColor {
    set {
      AoceWrapperPINVOKE.ChromaKeyParamet_ambientColor_set(swigCPtr, vec3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.ChromaKeyParamet_ambientColor_get(swigCPtr);
      vec3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new vec3(cPtr, false);
      return ret;
    } 
  }

  public float alphaCutoffMin {
    set {
      AoceWrapperPINVOKE.ChromaKeyParamet_alphaCutoffMin_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.ChromaKeyParamet_alphaCutoffMin_get(swigCPtr);
      return ret;
    } 
  }

  public float alphaScale {
    set {
      AoceWrapperPINVOKE.ChromaKeyParamet_alphaScale_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.ChromaKeyParamet_alphaScale_get(swigCPtr);
      return ret;
    } 
  }

  public float alphaExponent {
    set {
      AoceWrapperPINVOKE.ChromaKeyParamet_alphaExponent_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.ChromaKeyParamet_alphaExponent_get(swigCPtr);
      return ret;
    } 
  }

  public float despillScale {
    set {
      AoceWrapperPINVOKE.ChromaKeyParamet_despillScale_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.ChromaKeyParamet_despillScale_get(swigCPtr);
      return ret;
    } 
  }

  public float despillExponent {
    set {
      AoceWrapperPINVOKE.ChromaKeyParamet_despillExponent_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.ChromaKeyParamet_despillExponent_get(swigCPtr);
      return ret;
    } 
  }

  public ChromaKeyParamet() : this(AoceWrapperPINVOKE.new_ChromaKeyParamet(), true) {
  }

}
