//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ColorMatrixParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ColorMatrixParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ColorMatrixParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ColorMatrixParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_ColorMatrixParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float intensity {
    set {
      AoceWrapperPINVOKE.ColorMatrixParamet_intensity_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.ColorMatrixParamet_intensity_get(swigCPtr);
      return ret;
    } 
  }

  public Mat4x4 mat {
    set {
      AoceWrapperPINVOKE.ColorMatrixParamet_mat_set(swigCPtr, Mat4x4.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.ColorMatrixParamet_mat_get(swigCPtr);
      Mat4x4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Mat4x4(cPtr, false);
      return ret;
    } 
  }

  public ColorMatrixParamet() : this(AoceWrapperPINVOKE.new_ColorMatrixParamet(), true) {
  }

}
