//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CropParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CropParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CropParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CropParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_CropParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float centerX {
    set {
      AoceWrapperPINVOKE.CropParamet_centerX_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.CropParamet_centerX_get(swigCPtr);
      return ret;
    } 
  }

  public float centerY {
    set {
      AoceWrapperPINVOKE.CropParamet_centerY_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.CropParamet_centerY_get(swigCPtr);
      return ret;
    } 
  }

  public float width {
    set {
      AoceWrapperPINVOKE.CropParamet_width_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.CropParamet_width_get(swigCPtr);
      return ret;
    } 
  }

  public float height {
    set {
      AoceWrapperPINVOKE.CropParamet_height_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.CropParamet_height_get(swigCPtr);
      return ret;
    } 
  }

  public CropParamet() : this(AoceWrapperPINVOKE.new_CropParamet(), true) {
  }

}
