//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class GaussianBlurParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GaussianBlurParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GaussianBlurParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GaussianBlurParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_GaussianBlurParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int blurRadius {
    set {
      AoceWrapperPINVOKE.GaussianBlurParamet_blurRadius_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.GaussianBlurParamet_blurRadius_get(swigCPtr);
      return ret;
    } 
  }

  public float sigma {
    set {
      AoceWrapperPINVOKE.GaussianBlurParamet_sigma_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.GaussianBlurParamet_sigma_get(swigCPtr);
      return ret;
    } 
  }

  public GaussianBlurParamet() : this(AoceWrapperPINVOKE.new_GaussianBlurParamet(), true) {
  }

}
