//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class GLOutGpuTex : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GLOutGpuTex(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GLOutGpuTex obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GLOutGpuTex() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_GLOutGpuTex(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int image {
    set {
      AoceWrapperPINVOKE.GLOutGpuTex_image_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.GLOutGpuTex_image_get(swigCPtr);
      return ret;
    } 
  }

  public int width {
    set {
      AoceWrapperPINVOKE.GLOutGpuTex_width_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.GLOutGpuTex_width_get(swigCPtr);
      return ret;
    } 
  }

  public int height {
    set {
      AoceWrapperPINVOKE.GLOutGpuTex_height_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.GLOutGpuTex_height_get(swigCPtr);
      return ret;
    } 
  }

  public GLOutGpuTex() : this(AoceWrapperPINVOKE.new_GLOutGpuTex(), true) {
  }

}
