//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class HazeParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal HazeParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HazeParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~HazeParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_HazeParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float distance {
    set {
      AoceWrapperPINVOKE.HazeParamet_distance_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.HazeParamet_distance_get(swigCPtr);
      return ret;
    } 
  }

  public float slope {
    set {
      AoceWrapperPINVOKE.HazeParamet_slope_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.HazeParamet_slope_get(swigCPtr);
      return ret;
    } 
  }

  public HazeParamet() : this(AoceWrapperPINVOKE.new_HazeParamet(), true) {
  }

}
