//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IHSBLayer : ILayer {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IHSBLayer(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AoceWrapperPINVOKE.IHSBLayer_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IHSBLayer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_IHSBLayer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public virtual void reset() {
    AoceWrapperPINVOKE.IHSBLayer_reset(swigCPtr);
  }

  public virtual void rotateHue(float h) {
    AoceWrapperPINVOKE.IHSBLayer_rotateHue(swigCPtr, h);
  }

  public virtual void adjustSaturation(float h) {
    AoceWrapperPINVOKE.IHSBLayer_adjustSaturation(swigCPtr, h);
  }

  public virtual void adjustBrightness(float h) {
    AoceWrapperPINVOKE.IHSBLayer_adjustBrightness(swigCPtr, h);
  }

}
