//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ILGroupMetadata : ILMetadata {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ILGroupMetadata(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AoceWrapperPINVOKE.ILGroupMetadata_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ILGroupMetadata obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_ILGroupMetadata(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public virtual int getCount() {
    int ret = AoceWrapperPINVOKE.ILGroupMetadata_getCount(swigCPtr);
    return ret;
  }

  public virtual ILMetadata getLMetadata(int index) {
    global::System.IntPtr cPtr = AoceWrapperPINVOKE.ILGroupMetadata_getLMetadata(swigCPtr, index);
    ILMetadata ret = (cPtr == global::System.IntPtr.Zero) ? null : new ILMetadata(cPtr, false);
    return ret;
  }

  public virtual string getParametClass() {
    string ret = AoceWrapperPINVOKE.ILGroupMetadata_getParametClass(swigCPtr);
    return ret;
  }

}
