//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ImageType {
  other = 0,
  r8,
  rgba8,
  r16,
  bgra8,
  rgba32f,
  r32f,
  r32,
  rgba32
}
