//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IMediaPlayer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IMediaPlayer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IMediaPlayer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IMediaPlayer() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_IMediaPlayer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual void setObserver(IMediaPlayerObserver observer) {
    AoceWrapperPINVOKE.IMediaPlayer_setObserver(swigCPtr, IMediaPlayerObserver.getCPtr(observer));
  }

  public virtual void setDataSource(string path) {
    AoceWrapperPINVOKE.IMediaPlayer_setDataSource(swigCPtr, path);
  }

  public virtual void prepare(bool bAsync) {
    AoceWrapperPINVOKE.IMediaPlayer_prepare(swigCPtr, bAsync);
  }

  public virtual AudioStream getAudioStream() {
    AudioStream ret = new AudioStream(AoceWrapperPINVOKE.IMediaPlayer_getAudioStream(swigCPtr), false);
    return ret;
  }

  public virtual VideoStream getVideoStream() {
    VideoStream ret = new VideoStream(AoceWrapperPINVOKE.IMediaPlayer_getVideoStream(swigCPtr), false);
    return ret;
  }

  public virtual void start() {
    AoceWrapperPINVOKE.IMediaPlayer_start(swigCPtr);
  }

  public virtual void pause() {
    AoceWrapperPINVOKE.IMediaPlayer_pause(swigCPtr);
  }

  public virtual void stop() {
    AoceWrapperPINVOKE.IMediaPlayer_stop(swigCPtr);
  }

  public virtual void release() {
    AoceWrapperPINVOKE.IMediaPlayer_release(swigCPtr);
  }

}
