//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IOSBlurParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IOSBlurParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IOSBlurParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IOSBlurParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_IOSBlurParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float sacle {
    set {
      AoceWrapperPINVOKE.IOSBlurParamet_sacle_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.IOSBlurParamet_sacle_get(swigCPtr);
      return ret;
    } 
  }

  public GaussianBlurParamet blurParamet {
    set {
      AoceWrapperPINVOKE.IOSBlurParamet_blurParamet_set(swigCPtr, GaussianBlurParamet.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.IOSBlurParamet_blurParamet_get(swigCPtr);
      GaussianBlurParamet ret = (cPtr == global::System.IntPtr.Zero) ? null : new GaussianBlurParamet(cPtr, false);
      return ret;
    } 
  }

  public float saturation {
    set {
      AoceWrapperPINVOKE.IOSBlurParamet_saturation_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.IOSBlurParamet_saturation_get(swigCPtr);
      return ret;
    } 
  }

  public float range {
    set {
      AoceWrapperPINVOKE.IOSBlurParamet_range_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.IOSBlurParamet_range_get(swigCPtr);
      return ret;
    } 
  }

  public IOSBlurParamet() : this(AoceWrapperPINVOKE.new_IOSBlurParamet(), true) {
  }

}
