//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IOutputLayer : AOutputLayer {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IOutputLayer(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AoceWrapperPINVOKE.IOutputLayer_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IOutputLayer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_IOutputLayer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public virtual void setObserver(IOutputLayerObserver observer) {
    AoceWrapperPINVOKE.IOutputLayer_setObserver(swigCPtr, IOutputLayerObserver.getCPtr(observer));
  }

  public virtual void outDx11GpuTex(global::System.IntPtr device, global::System.IntPtr tex) {
    AoceWrapperPINVOKE.IOutputLayer_outDx11GpuTex(swigCPtr, device, tex);
  }

  public virtual void outGLGpuTex(GLOutGpuTex outTex, uint texType, int outIndex) {
    AoceWrapperPINVOKE.IOutputLayer_outGLGpuTex__SWIG_0(swigCPtr, GLOutGpuTex.getCPtr(outTex), texType, outIndex);
    if (AoceWrapperPINVOKE.SWIGPendingException.Pending) throw AoceWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void outGLGpuTex(GLOutGpuTex outTex, uint texType) {
    AoceWrapperPINVOKE.IOutputLayer_outGLGpuTex__SWIG_1(swigCPtr, GLOutGpuTex.getCPtr(outTex), texType);
    if (AoceWrapperPINVOKE.SWIGPendingException.Pending) throw AoceWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void outGLGpuTex(GLOutGpuTex outTex) {
    AoceWrapperPINVOKE.IOutputLayer_outGLGpuTex__SWIG_2(swigCPtr, GLOutGpuTex.getCPtr(outTex));
    if (AoceWrapperPINVOKE.SWIGPendingException.Pending) throw AoceWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

}
