//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ISoftEleganceLayer : ASoftEleganceLayer {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ISoftEleganceLayer(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AoceWrapperPINVOKE.ISoftEleganceLayer_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ISoftEleganceLayer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_ISoftEleganceLayer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public virtual void loadLookUp1(global::System.IntPtr data, int size) {
    AoceWrapperPINVOKE.ISoftEleganceLayer_loadLookUp1(swigCPtr, data, size);
  }

  public virtual void loadLookUp2(global::System.IntPtr data, int size) {
    AoceWrapperPINVOKE.ISoftEleganceLayer_loadLookUp2(swigCPtr, data, size);
  }

  public virtual IInputLayer getLookUpInputLayer1() {
    global::System.IntPtr cPtr = AoceWrapperPINVOKE.ISoftEleganceLayer_getLookUpInputLayer1(swigCPtr);
    IInputLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new IInputLayer(cPtr, false);
    return ret;
  }

  public virtual IInputLayer getLookUpInputLayer2() {
    global::System.IntPtr cPtr = AoceWrapperPINVOKE.ISoftEleganceLayer_getLookUpInputLayer2(swigCPtr);
    IInputLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new IInputLayer(cPtr, false);
    return ret;
  }

}
