//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IVideoDeviceObserver : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IVideoDeviceObserver(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IVideoDeviceObserver obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IVideoDeviceObserver() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_IVideoDeviceObserver(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual void onDeviceHandle(VideoHandleId id, int codeId) {
    if (SwigDerivedClassHasMethod("onDeviceHandle", swigMethodTypes0)) AoceWrapperPINVOKE.IVideoDeviceObserver_onDeviceHandleSwigExplicitIVideoDeviceObserver(swigCPtr, (int)id, codeId); else AoceWrapperPINVOKE.IVideoDeviceObserver_onDeviceHandle(swigCPtr, (int)id, codeId);
  }

  public virtual void onVideoFrame(VideoFrame frame) {
    if (SwigDerivedClassHasMethod("onVideoFrame", swigMethodTypes1)) AoceWrapperPINVOKE.IVideoDeviceObserver_onVideoFrameSwigExplicitIVideoDeviceObserver(swigCPtr, VideoFrame.getCPtr(frame)); else AoceWrapperPINVOKE.IVideoDeviceObserver_onVideoFrame(swigCPtr, VideoFrame.getCPtr(frame));
    if (AoceWrapperPINVOKE.SWIGPendingException.Pending) throw AoceWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void onDepthVideoFrame(VideoFrame colorFrame, VideoFrame depthFrame, global::System.IntPtr alignParamt) {
    if (SwigDerivedClassHasMethod("onDepthVideoFrame", swigMethodTypes2)) AoceWrapperPINVOKE.IVideoDeviceObserver_onDepthVideoFrameSwigExplicitIVideoDeviceObserver(swigCPtr, VideoFrame.getCPtr(colorFrame), VideoFrame.getCPtr(depthFrame), alignParamt); else AoceWrapperPINVOKE.IVideoDeviceObserver_onDepthVideoFrame(swigCPtr, VideoFrame.getCPtr(colorFrame), VideoFrame.getCPtr(depthFrame), alignParamt);
    if (AoceWrapperPINVOKE.SWIGPendingException.Pending) throw AoceWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public IVideoDeviceObserver() : this(AoceWrapperPINVOKE.new_IVideoDeviceObserver(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("onDeviceHandle", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateIVideoDeviceObserver_0(SwigDirectorMethodonDeviceHandle);
    if (SwigDerivedClassHasMethod("onVideoFrame", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateIVideoDeviceObserver_1(SwigDirectorMethodonVideoFrame);
    if (SwigDerivedClassHasMethod("onDepthVideoFrame", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateIVideoDeviceObserver_2(SwigDirectorMethodonDepthVideoFrame);
    AoceWrapperPINVOKE.IVideoDeviceObserver_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(IVideoDeviceObserver));
    return hasDerivedMethod;
  }

  private void SwigDirectorMethodonDeviceHandle(int id, int codeId) {
    onDeviceHandle((VideoHandleId)id, codeId);
  }

  private void SwigDirectorMethodonVideoFrame(global::System.IntPtr frame) {
    onVideoFrame(new VideoFrame(frame, true));
  }

  private void SwigDirectorMethodonDepthVideoFrame(global::System.IntPtr colorFrame, global::System.IntPtr depthFrame, global::System.IntPtr alignParamt) {
    onDepthVideoFrame(new VideoFrame(colorFrame, true), new VideoFrame(depthFrame, true), alignParamt);
  }

  public delegate void SwigDelegateIVideoDeviceObserver_0(int id, int codeId);
  public delegate void SwigDelegateIVideoDeviceObserver_1(global::System.IntPtr frame);
  public delegate void SwigDelegateIVideoDeviceObserver_2(global::System.IntPtr colorFrame, global::System.IntPtr depthFrame, global::System.IntPtr alignParamt);

  private SwigDelegateIVideoDeviceObserver_0 swigDelegate0;
  private SwigDelegateIVideoDeviceObserver_1 swigDelegate1;
  private SwigDelegateIVideoDeviceObserver_2 swigDelegate2;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(VideoHandleId), typeof(int) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(VideoFrame) };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] { typeof(VideoFrame), typeof(VideoFrame), typeof(global::System.IntPtr) };
}
