//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LayerFactory : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LayerFactory(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LayerFactory obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LayerFactory() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_LayerFactory(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual IInputLayer createInput() {
    global::System.IntPtr cPtr = AoceWrapperPINVOKE.LayerFactory_createInput(swigCPtr);
    IInputLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new IInputLayer(cPtr, false);
    return ret;
  }

  public virtual IOutputLayer createOutput() {
    global::System.IntPtr cPtr = AoceWrapperPINVOKE.LayerFactory_createOutput(swigCPtr);
    IOutputLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new IOutputLayer(cPtr, false);
    return ret;
  }

  public virtual IYUVLayer createYUV2RGBA() {
    global::System.IntPtr cPtr = AoceWrapperPINVOKE.LayerFactory_createYUV2RGBA(swigCPtr);
    IYUVLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new IYUVLayer(cPtr, false);
    return ret;
  }

  public virtual IYUVLayer createRGBA2YUV() {
    global::System.IntPtr cPtr = AoceWrapperPINVOKE.LayerFactory_createRGBA2YUV(swigCPtr);
    IYUVLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new IYUVLayer(cPtr, false);
    return ret;
  }

  public virtual IMapChannelLayer createMapChannel() {
    global::System.IntPtr cPtr = AoceWrapperPINVOKE.LayerFactory_createMapChannel(swigCPtr);
    IMapChannelLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new IMapChannelLayer(cPtr, false);
    return ret;
  }

  public virtual IFlipLayer createFlip() {
    global::System.IntPtr cPtr = AoceWrapperPINVOKE.LayerFactory_createFlip(swigCPtr);
    IFlipLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new IFlipLayer(cPtr, false);
    return ret;
  }

  public virtual ITransposeLayer createTranspose() {
    global::System.IntPtr cPtr = AoceWrapperPINVOKE.LayerFactory_createTranspose(swigCPtr);
    ITransposeLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new ITransposeLayer(cPtr, false);
    return ret;
  }

  public virtual IReSizeLayer createSize() {
    global::System.IntPtr cPtr = AoceWrapperPINVOKE.LayerFactory_createSize(swigCPtr);
    IReSizeLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new IReSizeLayer(cPtr, false);
    return ret;
  }

  public virtual IBlendLayer createBlend() {
    global::System.IntPtr cPtr = AoceWrapperPINVOKE.LayerFactory_createBlend(swigCPtr);
    IBlendLayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new IBlendLayer(cPtr, false);
    return ret;
  }

}
