//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Mat3x3 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Mat3x3(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Mat3x3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Mat3x3() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_Mat3x3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public vec3 col0 {
    set {
      AoceWrapperPINVOKE.Mat3x3_col0_set(swigCPtr, vec3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.Mat3x3_col0_get(swigCPtr);
      vec3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new vec3(cPtr, false);
      return ret;
    } 
  }

  public vec3 col1 {
    set {
      AoceWrapperPINVOKE.Mat3x3_col1_set(swigCPtr, vec3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.Mat3x3_col1_get(swigCPtr);
      vec3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new vec3(cPtr, false);
      return ret;
    } 
  }

  public vec3 col2 {
    set {
      AoceWrapperPINVOKE.Mat3x3_col2_set(swigCPtr, vec3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.Mat3x3_col2_get(swigCPtr);
      vec3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new vec3(cPtr, false);
      return ret;
    } 
  }

  public Mat3x3() : this(AoceWrapperPINVOKE.new_Mat3x3(), true) {
  }

}
