//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Mat4x4 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Mat4x4(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Mat4x4 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Mat4x4() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_Mat4x4(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public vec4 col0 {
    set {
      AoceWrapperPINVOKE.Mat4x4_col0_set(swigCPtr, vec4.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.Mat4x4_col0_get(swigCPtr);
      vec4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new vec4(cPtr, false);
      return ret;
    } 
  }

  public vec4 col1 {
    set {
      AoceWrapperPINVOKE.Mat4x4_col1_set(swigCPtr, vec4.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.Mat4x4_col1_get(swigCPtr);
      vec4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new vec4(cPtr, false);
      return ret;
    } 
  }

  public vec4 col2 {
    set {
      AoceWrapperPINVOKE.Mat4x4_col2_set(swigCPtr, vec4.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.Mat4x4_col2_get(swigCPtr);
      vec4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new vec4(cPtr, false);
      return ret;
    } 
  }

  public vec4 col3 {
    set {
      AoceWrapperPINVOKE.Mat4x4_col3_set(swigCPtr, vec4.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.Mat4x4_col3_get(swigCPtr);
      vec4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new vec4(cPtr, false);
      return ret;
    } 
  }

  public Mat4x4() : this(AoceWrapperPINVOKE.new_Mat4x4(), true) {
  }

}
