//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class NobleCornerDetectionParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NobleCornerDetectionParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NobleCornerDetectionParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NobleCornerDetectionParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_NobleCornerDetectionParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public HarrisDetectionBaseParamet harrisBase {
    set {
      AoceWrapperPINVOKE.NobleCornerDetectionParamet_harrisBase_set(swigCPtr, HarrisDetectionBaseParamet.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.NobleCornerDetectionParamet_harrisBase_get(swigCPtr);
      HarrisDetectionBaseParamet ret = (cPtr == global::System.IntPtr.Zero) ? null : new HarrisDetectionBaseParamet(cPtr, false);
      return ret;
    } 
  }

  public float sensitivity {
    set {
      AoceWrapperPINVOKE.NobleCornerDetectionParamet_sensitivity_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.NobleCornerDetectionParamet_sensitivity_get(swigCPtr);
      return ret;
    } 
  }

  public NobleCornerDetectionParamet() : this(AoceWrapperPINVOKE.new_NobleCornerDetectionParamet(), true) {
  }

}
