//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PixellateParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PixellateParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PixellateParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PixellateParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_PixellateParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float fractionalWidthOfPixel {
    set {
      AoceWrapperPINVOKE.PixellateParamet_fractionalWidthOfPixel_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.PixellateParamet_fractionalWidthOfPixel_get(swigCPtr);
      return ret;
    } 
  }

  public float aspectRatio {
    set {
      AoceWrapperPINVOKE.PixellateParamet_aspectRatio_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.PixellateParamet_aspectRatio_get(swigCPtr);
      return ret;
    } 
  }

  public PixellateParamet() : this(AoceWrapperPINVOKE.new_PixellateParamet(), true) {
  }

}
