//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PoissonParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PoissonParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PoissonParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PoissonParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_PoissonParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float percent {
    set {
      AoceWrapperPINVOKE.PoissonParamet_percent_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.PoissonParamet_percent_get(swigCPtr);
      return ret;
    } 
  }

  public int iterationNum {
    set {
      AoceWrapperPINVOKE.PoissonParamet_iterationNum_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.PoissonParamet_iterationNum_get(swigCPtr);
      return ret;
    } 
  }

  public PoissonParamet() : this(AoceWrapperPINVOKE.new_PoissonParamet(), true) {
  }

}
