//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PullSetting : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PullSetting(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PullSetting obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PullSetting() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_PullSetting(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int bAudio {
    set {
      AoceWrapperPINVOKE.PullSetting_bAudio_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.PullSetting_bAudio_get(swigCPtr);
      return ret;
    } 
  }

  public int bVideo {
    set {
      AoceWrapperPINVOKE.PullSetting_bVideo_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.PullSetting_bVideo_get(swigCPtr);
      return ret;
    } 
  }

  public PullSetting() : this(AoceWrapperPINVOKE.new_PullSetting(), true) {
  }

}
