//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PushStream : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PushStream(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PushStream obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PushStream() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_PushStream(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int bOpen {
    set {
      AoceWrapperPINVOKE.PushStream_bOpen_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.PushStream_bOpen_get(swigCPtr);
      return ret;
    } 
  }

  public PushSetting setting {
    set {
      AoceWrapperPINVOKE.PushStream_setting_set(swigCPtr, PushSetting.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.PushStream_setting_get(swigCPtr);
      PushSetting ret = (cPtr == global::System.IntPtr.Zero) ? null : new PushSetting(cPtr, false);
      return ret;
    } 
  }

  public PushStream() : this(AoceWrapperPINVOKE.new_PushStream(), true) {
  }

}
