//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PushSetting : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PushSetting(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PushSetting obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PushSetting() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_PushSetting(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int bAudio {
    set {
      AoceWrapperPINVOKE.PushSetting_bAudio_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.PushSetting_bAudio_get(swigCPtr);
      return ret;
    } 
  }

  public int bVideo {
    set {
      AoceWrapperPINVOKE.PushSetting_bVideo_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.PushSetting_bVideo_get(swigCPtr);
      return ret;
    } 
  }

  public VideoStream videoStream {
    set {
      AoceWrapperPINVOKE.PushSetting_videoStream_set(swigCPtr, VideoStream.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.PushSetting_videoStream_get(swigCPtr);
      VideoStream ret = (cPtr == global::System.IntPtr.Zero) ? null : new VideoStream(cPtr, false);
      return ret;
    } 
  }

  public AudioStream audioStream {
    set {
      AoceWrapperPINVOKE.PushSetting_audioStream_set(swigCPtr, AudioStream.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.PushSetting_audioStream_get(swigCPtr);
      AudioStream ret = (cPtr == global::System.IntPtr.Zero) ? null : new AudioStream(cPtr, false);
      return ret;
    } 
  }

  public int bCDN {
    set {
      AoceWrapperPINVOKE.PushSetting_bCDN_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.PushSetting_bCDN_get(swigCPtr);
      return ret;
    } 
  }

  public PushSetting() : this(AoceWrapperPINVOKE.new_PushSetting(), true) {
  }

}
