//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SizeScaleParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SizeScaleParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SizeScaleParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SizeScaleParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_SizeScaleParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int bLinear {
    set {
      AoceWrapperPINVOKE.SizeScaleParamet_bLinear_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.SizeScaleParamet_bLinear_get(swigCPtr);
      return ret;
    } 
  }

  public float fx {
    set {
      AoceWrapperPINVOKE.SizeScaleParamet_fx_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.SizeScaleParamet_fx_get(swigCPtr);
      return ret;
    } 
  }

  public float fy {
    set {
      AoceWrapperPINVOKE.SizeScaleParamet_fy_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.SizeScaleParamet_fy_get(swigCPtr);
      return ret;
    } 
  }

  public SizeScaleParamet() : this(AoceWrapperPINVOKE.new_SizeScaleParamet(), true) {
  }

}
