//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SkinToneParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SkinToneParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SkinToneParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SkinToneParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_SkinToneParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float skinToneAdjust {
    set {
      AoceWrapperPINVOKE.SkinToneParamet_skinToneAdjust_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.SkinToneParamet_skinToneAdjust_get(swigCPtr);
      return ret;
    } 
  }

  public float skinHue {
    set {
      AoceWrapperPINVOKE.SkinToneParamet_skinHue_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.SkinToneParamet_skinHue_get(swigCPtr);
      return ret;
    } 
  }

  public float skinHueThreshold {
    set {
      AoceWrapperPINVOKE.SkinToneParamet_skinHueThreshold_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.SkinToneParamet_skinHueThreshold_get(swigCPtr);
      return ret;
    } 
  }

  public float maxHueShift {
    set {
      AoceWrapperPINVOKE.SkinToneParamet_maxHueShift_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.SkinToneParamet_maxHueShift_get(swigCPtr);
      return ret;
    } 
  }

  public float maxSaturationShift {
    set {
      AoceWrapperPINVOKE.SkinToneParamet_maxSaturationShift_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.SkinToneParamet_maxSaturationShift_get(swigCPtr);
      return ret;
    } 
  }

  public int upperSkinToneColor {
    set {
      AoceWrapperPINVOKE.SkinToneParamet_upperSkinToneColor_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.SkinToneParamet_upperSkinToneColor_get(swigCPtr);
      return ret;
    } 
  }

  public SkinToneParamet() : this(AoceWrapperPINVOKE.new_SkinToneParamet(), true) {
  }

}
