//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SmoothToonParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SmoothToonParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SmoothToonParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SmoothToonParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_SmoothToonParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public GaussianBlurParamet blur {
    set {
      AoceWrapperPINVOKE.SmoothToonParamet_blur_set(swigCPtr, GaussianBlurParamet.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.SmoothToonParamet_blur_get(swigCPtr);
      GaussianBlurParamet ret = (cPtr == global::System.IntPtr.Zero) ? null : new GaussianBlurParamet(cPtr, false);
      return ret;
    } 
  }

  public ToonParamet toon {
    set {
      AoceWrapperPINVOKE.SmoothToonParamet_toon_set(swigCPtr, ToonParamet.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.SmoothToonParamet_toon_get(swigCPtr);
      ToonParamet ret = (cPtr == global::System.IntPtr.Zero) ? null : new ToonParamet(cPtr, false);
      return ret;
    } 
  }

  public SmoothToonParamet() : this(AoceWrapperPINVOKE.new_SmoothToonParamet(), true) {
  }

}
