//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TiltShiftParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TiltShiftParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TiltShiftParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TiltShiftParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_TiltShiftParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public GaussianBlurParamet blur {
    set {
      AoceWrapperPINVOKE.TiltShiftParamet_blur_set(swigCPtr, GaussianBlurParamet.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.TiltShiftParamet_blur_get(swigCPtr);
      GaussianBlurParamet ret = (cPtr == global::System.IntPtr.Zero) ? null : new GaussianBlurParamet(cPtr, false);
      return ret;
    } 
  }

  public float topFocusLevel {
    set {
      AoceWrapperPINVOKE.TiltShiftParamet_topFocusLevel_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.TiltShiftParamet_topFocusLevel_get(swigCPtr);
      return ret;
    } 
  }

  public float bottomFocusLevel {
    set {
      AoceWrapperPINVOKE.TiltShiftParamet_bottomFocusLevel_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.TiltShiftParamet_bottomFocusLevel_get(swigCPtr);
      return ret;
    } 
  }

  public float focusFallOffRate {
    set {
      AoceWrapperPINVOKE.TiltShiftParamet_focusFallOffRate_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.TiltShiftParamet_focusFallOffRate_get(swigCPtr);
      return ret;
    } 
  }

  public TiltShiftParamet() : this(AoceWrapperPINVOKE.new_TiltShiftParamet(), true) {
  }

}
