//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class UInt8Array : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UInt8Array(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UInt8Array obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UInt8Array() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_UInt8Array(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public UInt8Array(int nelements) : this(AoceWrapperPINVOKE.new_UInt8Array(nelements), true) {
  }

  public byte getitem(int index) {
    byte ret = AoceWrapperPINVOKE.UInt8Array_getitem(swigCPtr, index);
    return ret;
  }

  public void setitem(int index, byte value) {
    AoceWrapperPINVOKE.UInt8Array_setitem(swigCPtr, index, value);
  }

  public global::System.IntPtr cast() {
    global::System.IntPtr ret = AoceWrapperPINVOKE.UInt8Array_cast(swigCPtr);
    return ret;
  }

  public static UInt8Array frompointer(global::System.IntPtr t) {
    global::System.IntPtr cPtr = AoceWrapperPINVOKE.UInt8Array_frompointer(t);
    UInt8Array ret = (cPtr == global::System.IntPtr.Zero) ? null : new UInt8Array(cPtr, false);
    return ret;
  }

}
