//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vec3 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vec3(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vec3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vec3() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_vec3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float x {
    set {
      AoceWrapperPINVOKE.vec3_x_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.vec3_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      AoceWrapperPINVOKE.vec3_y_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.vec3_y_get(swigCPtr);
      return ret;
    } 
  }

  public float z {
    set {
      AoceWrapperPINVOKE.vec3_z_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.vec3_z_get(swigCPtr);
      return ret;
    } 
  }

  public vec3() : this(AoceWrapperPINVOKE.new_vec3(), true) {
  }

}
