//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vec4 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vec4(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vec4 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vec4() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_vec4(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float x {
    set {
      AoceWrapperPINVOKE.vec4_x_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.vec4_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      AoceWrapperPINVOKE.vec4_y_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.vec4_y_get(swigCPtr);
      return ret;
    } 
  }

  public float z {
    set {
      AoceWrapperPINVOKE.vec4_z_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.vec4_z_get(swigCPtr);
      return ret;
    } 
  }

  public float w {
    set {
      AoceWrapperPINVOKE.vec4_w_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.vec4_w_get(swigCPtr);
      return ret;
    } 
  }

  public vec4() : this(AoceWrapperPINVOKE.new_vec4__SWIG_0(), true) {
  }

  public vec4(float x, float y, float z, float w) : this(AoceWrapperPINVOKE.new_vec4__SWIG_1(x, y, z, w), true) {
  }

  public vec4(vec3 vec, float w) : this(AoceWrapperPINVOKE.new_vec4__SWIG_2(vec3.getCPtr(vec), w), true) {
    if (AoceWrapperPINVOKE.SWIGPendingException.Pending) throw AoceWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

}
