//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VideoType {
  other = 0,
  nv12,
  yuv2I,
  yvyuI,
  uyvyI,
  mjpg,
  rgb8,
  argb8,
  rgba8,
  bgra8,
  depth16u,
  yuy2P,
  yuv420P
}
