//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VideoHandleId {
  none = 0,
  open = 1,
  close = 2,
  unKnownError = -1,
  lost = -2,
  openFailed = -3
}
