//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VideoStream : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VideoStream(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VideoStream obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VideoStream() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_VideoStream(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VideoCodec codec {
    set {
      AoceWrapperPINVOKE.VideoStream_codec_set(swigCPtr, (int)value);
    } 
    get {
      VideoCodec ret = (VideoCodec)AoceWrapperPINVOKE.VideoStream_codec_get(swigCPtr);
      return ret;
    } 
  }

  public int width {
    set {
      AoceWrapperPINVOKE.VideoStream_width_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.VideoStream_width_get(swigCPtr);
      return ret;
    } 
  }

  public int height {
    set {
      AoceWrapperPINVOKE.VideoStream_height_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.VideoStream_height_get(swigCPtr);
      return ret;
    } 
  }

  public int fps {
    set {
      AoceWrapperPINVOKE.VideoStream_fps_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.VideoStream_fps_get(swigCPtr);
      return ret;
    } 
  }

  public int bitrate {
    set {
      AoceWrapperPINVOKE.VideoStream_bitrate_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.VideoStream_bitrate_get(swigCPtr);
      return ret;
    } 
  }

  public VideoType videoType {
    set {
      AoceWrapperPINVOKE.VideoStream_videoType_set(swigCPtr, (int)value);
    } 
    get {
      VideoType ret = (VideoType)AoceWrapperPINVOKE.VideoStream_videoType_get(swigCPtr);
      return ret;
    } 
  }

  public VideoStream() : this(AoceWrapperPINVOKE.new_VideoStream(), true) {
  }

}
