//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VideoFormat : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VideoFormat(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VideoFormat obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VideoFormat() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_VideoFormat(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int index {
    set {
      AoceWrapperPINVOKE.VideoFormat_index_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.VideoFormat_index_get(swigCPtr);
      return ret;
    } 
  }

  public int width {
    set {
      AoceWrapperPINVOKE.VideoFormat_width_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.VideoFormat_width_get(swigCPtr);
      return ret;
    } 
  }

  public int height {
    set {
      AoceWrapperPINVOKE.VideoFormat_height_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.VideoFormat_height_get(swigCPtr);
      return ret;
    } 
  }

  public int fps {
    set {
      AoceWrapperPINVOKE.VideoFormat_fps_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.VideoFormat_fps_get(swigCPtr);
      return ret;
    } 
  }

  public VideoType videoType {
    set {
      AoceWrapperPINVOKE.VideoFormat_videoType_set(swigCPtr, (int)value);
    } 
    get {
      VideoType ret = (VideoType)AoceWrapperPINVOKE.VideoFormat_videoType_get(swigCPtr);
      return ret;
    } 
  }

  public VideoFormat() : this(AoceWrapperPINVOKE.new_VideoFormat(), true) {
  }

}
