//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VideoFrame : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VideoFrame(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VideoFrame obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VideoFrame() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_VideoFrame(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int width {
    set {
      AoceWrapperPINVOKE.VideoFrame_width_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.VideoFrame_width_get(swigCPtr);
      return ret;
    } 
  }

  public int height {
    set {
      AoceWrapperPINVOKE.VideoFrame_height_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.VideoFrame_height_get(swigCPtr);
      return ret;
    } 
  }

  public long timeStamp {
    set {
      AoceWrapperPINVOKE.VideoFrame_timeStamp_set(swigCPtr, value);
    } 
    get {
      long ret = AoceWrapperPINVOKE.VideoFrame_timeStamp_get(swigCPtr);
      return ret;
    } 
  }

  public VideoType videoType {
    set {
      AoceWrapperPINVOKE.VideoFrame_videoType_set(swigCPtr, (int)value);
    } 
    get {
      VideoType ret = (VideoType)AoceWrapperPINVOKE.VideoFrame_videoType_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_unsigned_char data {
    set {
      AoceWrapperPINVOKE.VideoFrame_data_set(swigCPtr, SWIGTYPE_p_p_unsigned_char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.VideoFrame_data_get(swigCPtr);
      SWIGTYPE_p_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_unsigned_char(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_int dataAlign {
    set {
      AoceWrapperPINVOKE.VideoFrame_dataAlign_set(swigCPtr, SWIGTYPE_p_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AoceWrapperPINVOKE.VideoFrame_dataAlign_get(swigCPtr);
      SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
      return ret;
    } 
  }

  public VideoFrame() : this(AoceWrapperPINVOKE.new_VideoFrame(), true) {
  }

}
