//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class WhiteBalanceParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal WhiteBalanceParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(WhiteBalanceParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~WhiteBalanceParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_WhiteBalanceParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float temperature {
    set {
      AoceWrapperPINVOKE.WhiteBalanceParamet_temperature_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.WhiteBalanceParamet_temperature_get(swigCPtr);
      return ret;
    } 
  }

  public float tint {
    set {
      AoceWrapperPINVOKE.WhiteBalanceParamet_tint_set(swigCPtr, value);
    } 
    get {
      float ret = AoceWrapperPINVOKE.WhiteBalanceParamet_tint_get(swigCPtr);
      return ret;
    } 
  }

  public WhiteBalanceParamet() : this(AoceWrapperPINVOKE.new_WhiteBalanceParamet(), true) {
  }

}
