//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class YUVParamet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal YUVParamet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(YUVParamet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~YUVParamet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AoceWrapperPINVOKE.delete_YUVParamet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VideoType type {
    set {
      AoceWrapperPINVOKE.YUVParamet_type_set(swigCPtr, (int)value);
    } 
    get {
      VideoType ret = (VideoType)AoceWrapperPINVOKE.YUVParamet_type_get(swigCPtr);
      return ret;
    } 
  }

  public int special {
    set {
      AoceWrapperPINVOKE.YUVParamet_special_set(swigCPtr, value);
    } 
    get {
      int ret = AoceWrapperPINVOKE.YUVParamet_special_get(swigCPtr);
      return ret;
    } 
  }

  public YUVParamet() : this(AoceWrapperPINVOKE.new_YUVParamet(), true) {
  }

}
